# Generated by Django 4.2.7 on 2026-01-31 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название учебного года')),
                ('start_year', models.IntegerField(verbose_name='Год начала')),
                ('end_year', models.IntegerField(verbose_name='Год окончания')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущий учебный год')),
                ('is_planned', models.BooleanField(default=False, verbose_name='Запланирован')),
            ],
            options={
                'verbose_name': 'Учебный год',
                'verbose_name_plural': 'Учебные годы',
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='BachelorProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код направления')),
                ('name', models.CharField(max_length=200, verbose_name='Название направления')),
            ],
            options={
                'verbose_name': 'Направление бакалавриата',
                'verbose_name_plural': 'Направления бакалавриата',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Номер курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_admission', models.IntegerField(verbose_name='Год набора')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активный'), ('archived', 'Архивный')], default='active', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.academicyear', verbose_name='Учебный год')),
                ('bachelor_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.bachelorprogram', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
            },
        ),
        migrations.CreateModel(
            name='CurriculumSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_hours', models.IntegerField(default=0, verbose_name='Лекционные часы')),
                ('practice_hours', models.IntegerField(default=0, verbose_name='Практические часы')),
                ('lab_hours', models.IntegerField(default=0, verbose_name='Лабораторные часы')),
                ('is_stream', models.BooleanField(default=False, verbose_name='Потоковая дисциплина')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.course', verbose_name='Курс')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.curriculum', verbose_name='Учебный план')),
            ],
            options={
                'verbose_name': 'Дисциплина в плане',
                'verbose_name_plural': 'Дисциплины в плане',
            },
        ),
        migrations.CreateModel(
            name='CurriculumSubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_lecture', models.IntegerField(default=0, verbose_name='Лекционные часы')),
                ('hours_practice', models.IntegerField(default=0, verbose_name='Практические часы')),
                ('hours_lab', models.IntegerField(default=0, verbose_name='Лабораторные часы')),
                ('curriculum_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.curriculumsubject', verbose_name='Дисциплина в плане')),
            ],
            options={
                'verbose_name': 'Группа для дисциплины',
                'verbose_name_plural': 'Группы для дисциплин',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кафедры')),
                ('short_name', models.CharField(max_length=50, verbose_name='Короткое название')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название факультета')),
                ('short_name', models.CharField(max_length=50, verbose_name='Короткое название')),
                ('dean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_dean', to=settings.AUTH_USER_MODEL, verbose_name='Декан')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='NextYearPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'На рассмотрении'), ('approved_dean', 'Утверждено деканом'), ('approved_rector', 'Утверждено ректором'), ('rejected', 'Отклонено')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.academicyear', verbose_name='Учебный год')),
                ('approved_by_dean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_approved_plans', to=settings.AUTH_USER_MODEL)),
                ('approved_by_rector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rector_approved_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'План на следующий год',
                'verbose_name_plural': 'Планы на следующий год',
                'unique_together': {('department', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, '1'), (2, '2')], verbose_name='Номер семестра')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.academicyear', verbose_name='Учебный год')),
            ],
            options={
                'verbose_name': 'Семестр',
                'verbose_name_plural': 'Семестры',
                'unique_together': {('academic_year', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('workload_hours', models.IntegerField(default=18, verbose_name='Нагрузка (часов в неделю)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.department', verbose_name='Кафедра')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='TeacherWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_lecture', models.IntegerField(default=0, verbose_name='Лекционные часы')),
                ('hours_practice', models.IntegerField(default=0, verbose_name='Практические часы')),
                ('hours_lab', models.IntegerField(default=0, verbose_name='Лабораторные часы')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('approved', 'Утверждено'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], default='planned', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.academicyear', verbose_name='Учебный год')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_workloads', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил')),
                ('curriculum_subject_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.curriculumsubjectgroup', verbose_name='Дисциплина и группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Нагрузка преподавателя',
                'verbose_name_plural': 'Нагрузки преподавателей',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('dean', 'Декан'), ('head', 'Заведующий кафедрой'), ('teacher', 'Преподаватель'), ('planner', 'Планировщик')], default='teacher', max_length=20, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hours_distribution.department', verbose_name='Кафедра')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hours_distribution.faculty', verbose_name='Факультет')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='TimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('hours_spent', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Затрачено часов')),
                ('activity_type', models.CharField(choices=[('lecture', 'Лекция'), ('practice', 'Практика'), ('lab', 'Лабораторная'), ('preparation', 'Подготовка'), ('consultation', 'Консультация'), ('checking', 'Проверка работ')], max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.teacher', verbose_name='Преподаватель')),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.teacherworkload', verbose_name='Нагрузка')),
            ],
            options={
                'verbose_name': 'Учет времени',
                'verbose_name_plural': 'Учет времени',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название дисциплины')),
                ('code', models.CharField(max_length=50, verbose_name='Код дисциплины')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название группы')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код группы')),
                ('group_type', models.CharField(choices=[('regular', 'Обычная группа'), ('stream', 'Потоковая группа'), ('subgroup', 'Подгруппа')], default='regular', max_length=20, verbose_name='Тип группы')),
                ('year_of_admission', models.IntegerField(verbose_name='Год набора')),
                ('students_count', models.IntegerField(default=0, verbose_name='Количество студентов')),
                ('max_students', models.IntegerField(default=25, verbose_name='Максимальное количество студентов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная группа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bachelor_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.bachelorprogram', verbose_name='Направление')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Группа студентов',
                'verbose_name_plural': 'Группы студентов',
                'ordering': ['-year_of_admission', 'course__number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StreamGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название потока')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Код потока')),
                ('total_students', models.IntegerField(default=0, verbose_name='Общее количество студентов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.academicyear', verbose_name='Учебный год')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.course', verbose_name='Курс')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.semester', verbose_name='Семестр')),
                ('student_groups', models.ManyToManyField(to='hours_distribution.studentgroup', verbose_name='Группы в потоке')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.subject', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Поточная группа',
                'verbose_name_plural': 'Поточные группы',
            },
        ),
        migrations.CreateModel(
            name='PlannedWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_lecture', models.IntegerField(default=0, verbose_name='Лекционные часы')),
                ('hours_practice', models.IntegerField(default=0, verbose_name='Практические часы')),
                ('hours_lab', models.IntegerField(default=0, verbose_name='Лабораторные часы')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.course', verbose_name='Курс')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_workloads', to='hours_distribution.nextyearplan')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.semester', verbose_name='Семестр')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.subject', verbose_name='Дисциплина')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Запланированная нагрузка',
                'verbose_name_plural': 'Запланированные нагрузки',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.faculty', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head', to=settings.AUTH_USER_MODEL, verbose_name='Заведующий кафедрой'),
        ),
        migrations.AddField(
            model_name='curriculumsubjectgroup',
            name='stream_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.streamgroup', verbose_name='Поточная группа'),
        ),
        migrations.AddField(
            model_name='curriculumsubjectgroup',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.studentgroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.department', verbose_name='Кафедра'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.semester', verbose_name='Семестр'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.subject', verbose_name='Дисциплина'),
        ),
        migrations.AddField(
            model_name='bachelorprogram',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.faculty', verbose_name='Факультет'),
        ),
        migrations.CreateModel(
            name='CurriculumSubjectStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.curriculumsubject')),
                ('stream_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.streamgroup')),
            ],
            options={
                'verbose_name': 'Связь дисциплины с потоком',
                'verbose_name_plural': 'Связи дисциплин с потоками',
                'unique_together': {('curriculum_subject', 'stream_group')},
            },
        ),
        migrations.AddConstraint(
            model_name='curriculumsubjectgroup',
            constraint=models.CheckConstraint(check=models.Q(('student_group__isnull', False), ('stream_group__isnull', False), _connector='OR'), name='at_least_one_group'),
        ),
    ]
