# Generated by Django 4.2.7 on 2026-02-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hours_distribution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamgroup',
            name='subject',
        ),
        migrations.AddField(
            model_name='streamgroup',
            name='bachelor_program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hours_distribution.bachelorprogram', verbose_name='Направление'),
            preserve_default=False,
        ),
    ]
