# Generated by Django 4.2.7 on 2026-02-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours_distribution', '0002_remove_streamgroup_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], verbose_name='Номер семестра'),
        ),
    ]
